# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/controle_estoque
spring.datasource.username=root
spring.datasource.password=ifsp

# Dialeto do Hibernate (MySQL/MariaDB)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Atualização automática das tabelas (usado para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
